config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  get 'comments/create'

  get 'users/show'

  get 'user/show'

  root :to => 'images#index'
  #
  # get 'images/new'
  #
  # get 'images/create'
  #
  # get 'images/show'
  #
  # get 'images/destroy'

  devise_for :users

  resources :users do
      resources :images do
        resources :comments
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  helper_method :is_admin?

  def is_admin?
    current_user && current_user.admin
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @image = Image.find(params[:image_id])
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = Image.find(params[:image_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = @user.id
    @comment.image_id = @image.id
    binding.pry
    if @comment.save
      flash[:notice] = "Comment successfully added!"
      redirect_to user_image_path(@user,@image)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @image = Image.find(params[:image_id])
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to '/'
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :image_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @image = @user.images.first
    @images = Image.all
  end

  def new
    @user = User.find(params[:user_id])
    @image = @user.images.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      flash[:notice] = "Review successfully added!"
      redirect_to user_images_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    @comments = Comment.where(image_id: @image.id)
  end

  def destroy
    @user = current_user
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to '/'
  end

private
  def image_params
    params.require(:image).permit(:url, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @images = @user.images
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@user,@image,@comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Add comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<br>

<img src="<%=@image.url%>" alt="">

<h4>comment by: <%= @user.email %></h4>

<% if current_user && is_admin? %>
  <h4><%= @comment.content %></h4>
<% end %>

<% if current_user && is_admin? %>
  <%= link_to 'Delete Comment', user_image_comment_path, :method => 'delete' %>
<% end %>

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>

<%= form_for [@user,@image] do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/images/index.html.erb
<h1>Welcome to ShinTastic Wedding Photography</h1>

<h3>About us:</h3>
<h4>Founded by David Shin back in 2012, Shintastic Wedding Photography has been delivering top quality wedding photos to couples all around the world. Check out our page to see some the work of our talented photographers. </h4>
<h4>if you are looking to hire us, please send us a message with your details to davidshin@gmail.com or email the photographers directly!</h4>

<img src="http://www.photolakedistrict.co.uk/wp-content/uploads/UK-Castle-Wedding-Photographer.jpg" alt="">

<h4>Certified Photographers</h4>
<% @users.each do |user| %>
  <% if user.admin %>
    <%= link_to user.email, user_path(user) %>
  <% end %>
<% end %>

<br>
<hr>
<h3>Check out our photos from our photographers</h3>
<% @images.each do |image| %>
<a href='/users/<%= @user.id %>/images/<%= image.id %>'><img src="<%= image.url %>" alt=""></a>
<% end %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<br>
<h3>Photo by: <%=@user.email%></h3>
<img src="<%=@image.url%>" alt="">
<br>
<% if current_user && is_admin? %>
  <%= link_to 'Delete Image', user_image_path, :method => 'delete'%>
<% end %>
<br>
<h4>Comments</h4>
<% @comments.each do |comment| %>
  <p><%= link_to comment.content, user_image_comment_path(@user.id, @image.id,comment.id)%></p>

<% end %>

<%= link_to 'New Comment', new_user_image_comment_path(@user,@image) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShintasticWeddingPhotos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">


      <% if current_user && is_admin?%>
        <%= link_to "Home", '/' %> | <%= link_to current_user.email, user_path(current_user) %> | <%= link_to "Sign out", destroy_user_session_path, :method =>'delete' %> | ADMIN
      <% elsif current_user %>
        <%= link_to "Home", '/' %> | <%= link_to current_user.email, user_path(current_user) %> | <%= link_to "Sign out", destroy_user_session_path, :method =>'delete' %>
      <% else %>
        <%= link_to "Home", '/' %> | <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
  <% if @images.length>0 %>
    <% @images.each do |image| %>
      <a href='/users/<%= @user.id %>/images/<%= image.id %>'><img src="<%=image.url%>" alt=""></a>
    <% end %>
  <% else %>
    <p>This photographer has no images yet</p>
  <% end %>
<hr>
<% if current_user && is_admin? %>
  <%= link_to 'New Image', new_user_image_path(@user) %>
<% end %>